apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-node
  labels:
    app: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: nodeapp
        image: mohanhariharan/node-app
        ports:
        - containerPort: 8080

